services:
  frontend:
    container_name: node
    build:
      context: ./frontend
    ports:
      - "3003:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    secrets:
      - database_url
      - auth_secret
      - auth_trust_host
      - auth_google_id
      - auth_google_secret
      - auth_github_id
      - auth_github_secret
      - auth_resend_key
      - aws_access_key_id
      - aws_secret_access_key
      - postgres_password
      - auth_url
    volumes:
      - type: bind
        source: ./frontend/public/
        target: /app/public/
    restart:
      always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-nutrition
      - shared-caddy-network

  db:
    image: postgres:14
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-liuhaochen}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: openfood_data
    secrets:
      - postgres_password
    restart:
      always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "liuhaochen", "-d", "openfood_data"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-nutrition

  otel-collector:
    container_name: otel
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"   # For OTLP gRPC
      - "4318:4318"   # For OTLP HTTP
    networks:
      - app-nutrition

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - app-nutrition
    
volumes:
  pgdata:
  caddy_data:
  caddy_config:

secrets:
  database_url:
    file: ./secrets/database_url
  auth_secret:
    file: ./secrets/auth_secret
  auth_trust_host:
    file: ./secrets/auth_trust_host
  auth_google_id:
    file: ./secrets/auth_google_id
  auth_google_secret:
    file: ./secrets/auth_google_secret
  auth_github_id:
    file: ./secrets/auth_github_id
  auth_github_secret:
    file: ./secrets/auth_github_secret
  auth_resend_key:
    file: ./secrets/auth_resend_key
  aws_access_key_id:
    file: ./secrets/aws_access_key_id
  aws_secret_access_key:
    file: ./secrets/aws_secret_access_key
  postgres_password:
    file: ./secrets/postgres_password
  auth_url:
    file: ./secrets/auth_url

  
networks:
  app-nutrition:
  shared-caddy-network:
    external: true

